# Generated by Django 4.2 on 2023-05-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_showreply_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created',
        ),
    ]
